# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\draft.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from helper import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 861)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputTokens = QtWidgets.QTextEdit(self.centralwidget)
        self.InputTokens.setGeometry(QtCore.QRect(11, 21, 261, 521))
        self.InputTokens.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.InputTokens.setObjectName("InputTokens")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 550, 261, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.probingResult = QtWidgets.QLabel(self.centralwidget)
        self.probingResult.setGeometry(QtCore.QRect(10, 600, 261, 201))
        self.probingResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.probingResult.setWordWrap(True)
        self.probingResult.setObjectName("probingResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # --------------------------------- My code block START ---------------------------------
    def update(self):
        # This updates the size of the label to fit its content
        self.probingResult.adjustSize()

    # We need to take the input tokens list FROM THE TEXTBOX!
    # And then do the Program() function on it.

    def Parseclicked(self):
        # taking TokenText from text box
        self.InputTokensText = self.InputTokens.toPlainText()
        self.TokensPlainText = self.InputTokensText  # TokenText from text box
        self.tokensList = GetTokensListFromPlainText(
            self.TokensPlainText)  # Making list of tokens
        self.probingResult.setText(str(Parse(self.tokensList)))
        self.update()
    # --------------------------------- My code block END ---------------------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OurParser"))
        self.InputTokens.setToolTip(_translate("MainWindow", "Write the list of tokens here"))
        self.InputTokens.setStatusTip(_translate("MainWindow", "Here we enter the list of tokens to be passed on to OurParser"))
        self.InputTokens.setPlaceholderText(_translate("MainWindow", "Input list of tokens (each on a separate line)"))
        self.pushButton.setText(_translate("MainWindow", "Parse"))
        self.probingResult.setText(_translate("MainWindow", "Syntax checking result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
